Tried to update to Neo4j 1.4 (not working)
Lucene indexing do not run in OSGi.
java.lang.IllegalArgumentException: No index provider 'lucene' found

Issue posted to Neo4j mailing list.